accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('users/', include([
        path('my-courses', views.EnrolledCoursesListView.as_view(), name='enrolled-courses'),
        path('my-courses/<slug:slug>/view', views.StartLessonView.as_view(), name='course-lessons'),
        path('my-courses/<slug:slug>/lessons/<int:id>', views.LessonView.as_view(), name='course-lessons-single'),
        path('user', views.UserUpdateView.as_view(), name='my-user'),
        path('my-profile', views.ProfileUpdateView.as_view(), name='my-profile'),
    ])),
]

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('courses/<slug:slug>/edit', CourseUpdateView.as_view(), name='course-edit'),
    path('courses/create', CourseCreateView.as_view(), name='course-create'),
    path('courses/lessons/<int:pk>/edit', LessonUpdateView.as_view(), name='course-lesson-edit'),
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='course-details'),
    path('courses/<slug:slug>/lessons', LessonsListView.as_view(), name='course-lessons'),
    path('courses/<slug:slug>/category', CoursesByCategoryListView.as_view(), name='course-by-category'),
]

lms/urls.py
from django.urls import path
from .views import *

app_name = 'lms'

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='search'),
]

lmspro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lmspro import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('lms.urls')),
    path('', include('courses.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/lessons/lesson_form.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load total_minutes %}

{% block content %}

<section class="user-dashboard-area">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="user-dashboard-box">
                    <div class="user-dashboard-sidebar">
                        <div class="user-box">
                            <img src="/media/{{ course.thumbnail }}" alt="" class="img-fluid">
                            <div class="name">
                                <div class="name">
                                    {{ course.title }}
                                </div>
                            </div>
                        </div>
                        <div class="user-dashboard-menu">
                            <ul>
                                <li >

                                    <a href="{% url 'courses:course-edit' course.slug %}">Temel Bilgiler</a>
                                </li>
                                <li >
                                    <a href="{% url 'accounts:my-profile' %}">Modüller</a>
                                </li>
                                <li >
                                    <a href="{% url 'accounts:my-profile' %}">Bölümler</a>
                                </li>
                                <li class="active"  >

                                    <a href="{% url 'courses:course-lessons' course.slug %}">Dersler</a>
                                </li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="user-dashboard-content">
                        <div class="content-title-box">
                            <div class="title">Ders Bilgileri</div>
                            <div class="subtitle">Kurs Detayı için ders içeriğini oluşturun.
                            </div>
                        </div>
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        <hr>
                        <form action="#" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            
                            <div class="content-box">
                                <div class="basic-group">
                                    {{ form|crispy }}
                                </div>
                                
                            </div>
                            <div class="content-update-box">
                                <button type="submit" class="btn">Güncelle</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/lessons/lessons_by_course.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            <div class="accordion" id="accordionExample">
                <div class="card" style="margin:10px 0;">

                    <div id="" class="collapse show" aria-labelledby="" data-parent="#accordionExample">
                        <div class="card-body" style="padding:0;">
                            <table style="width: 100%;">

                                {% for lesson in lessons %}

                                <tr style="width: 100%; padding: 5px 0px;">
                                    <td style="text-align: left;padding:10px; border-bottom:1px solid #ccc;">
                                        <a href="{% url 'accounts:course-lessons-single' slug=course.slug id=lesson.id %}"
                                            id="{{ lesson.id }}">
                                            <i class="fa fa-play"
                                                style="font-size: 12px;color: #909090;padding: 10px;"></i>
                                            {{ lesson.title }}
                                        </a>
                                    </td>
                                    <td style="text-align: right; padding:10px; border-bottom:1px solid #ccc;">
                                        <span class="lesson_duration">
                                            {{ lesson.duration | floatformat:2 }}
                                        </span>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- . -->
        <div class="col-9">
            <div class="card mt-3 tab-card">
                <div class="card-header tab-card-header">
                    <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link" id="one-tab" data-toggle="tab" href="#one" role="tab"
                                aria-controls="One" aria-selected="true">Videolar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="two-tab" data-toggle="tab" href="#two" role="tab"
                                aria-controls="Two" aria-selected="false">Dokümanlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="three-tab" data-toggle="tab" href="#three" role="tab"
                                aria-controls="Three" aria-selected="false">Uygulama</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="four-tab" data-toggle="tab" href="#four" role="tab"
                                aria-controls="Four" aria-selected="false">Ödevler</a>
                        </li>
                    </ul>
                </div>

                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active p-3" id="one" role="tabpanel" aria-labelledby="one-tab">
                        <!-- <h5 class="card-title">Videolar</h5> -->
                        <div class="col-lg-12" id="video_player_area">
                            <div class="" style="background-color: #333;">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe width="100%" height="500" class="embed-responsive-item"
                                        src=" {{ lesson.video_url }}" frameborder="0" allowfullscreen>
                                    </iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade p-3" id="two" role="tabpanel" aria-labelledby="two-tab">
                        <!-- <h5 class="card-title">Dokümanlar</h5> -->
                        <div class="col-lg-12" id="documents_area">
                            <div class="" style="background-color: #333;">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <embed width="100%" height="500" class="embed-responsive-item"
                                        src="/media/{{ lesson.documents }}" frameborder="0" allowfullscreen>
                                </embed>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade p-3" id="three" role="tabpanel" aria-labelledby="three-tab">
                        <div class="col-lg-12" id="experience_area">
                            <div class="" style="background-color: #333;">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe width="100%" height="500" class="embed-responsive-item" onmouseover="setFocus();" id="experience_area_frame"
                                        src="{{ lesson.handson_url }}" frameborder="0" allowfullscreen>
                                </iframe>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="tab-pane fade p-3" id="four" role="tabpanel" aria-labelledby="four-tab">
                        <h5 class="card-title">Ödevler</h5>
                        
                    </div>

                </div>
            </div>
        </div>
        <!-- . -->
    </div>
</div>

{% endblock %}

templates/lessons/lessons_list_by_course.html
{% extends 'layouts/base.html' %}

{% block content %}

<section class="user-dashboard-area">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="user-dashboard-box">
                    <div class="user-dashboard-sidebar">
                        <div class="user-box">
                            <img src="/media/{{ course.thumbnail }}" alt="" class="img-fluid">
                            <div class="name">
                                <div class="name">
                                    {{ course.title }}
                                </div>
                            </div>
                        </div>
                        <div class="user-dashboard-menu">
                            <ul>
                                <li >
                                    <a href="{% url 'courses:course-edit' course.slug %}">Temel Bilgiler</a>
                                </li>
                                <li >
                                    <a href="{% url 'accounts:my-profile' %}">Modüller</a>
                                </li>
                                <li >
                                    <a href="{% url 'accounts:my-profile' %}">Bölümler</a>
                                </li>
                                <li class="active"  >
                                    <a href="{% url 'courses:course-lessons' course.slug %}">Dersler</a>
                                </li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="user-dashboard-content">
                        <div class="content-title-box">
                            <div class="title">Ders Bilgileri</div>
                            <div class="subtitle">Kurs Detayı için ders içeriğini oluşturun.
                            </div>
                        </div>
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        <hr>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="accordion" id="accordionExample">
                                        <div class="card" style="margin:10px 0;">
                    
                                            <div id="" class="collapse show"
                                                 aria-labelledby="" data-parent="#accordionExample">
                                                <div class="card-body" style="padding:0;">
                                                    <table style="width: 100%;">
                    
                                                        {% for lesson in lessons %}
                    
                                                            <tr style="width: 100%; padding: 5px 0px;">
                                                                <td style="text-align: left;padding:10px; border-bottom:1px solid #ccc;">
                                                                    <a href="{% url 'courses:course-lesson-edit' pk=lesson.id %}"
                                                                       id="{{ lesson.id }}">
                                                                        <i class="fa fa-play"
                                                                           style="font-size: 12px;color: #909090;padding: 10px;"></i>
                                                                        {{ lesson.title }}
                                                                    </a>
                                                                </td>
                                                                <td style="text-align: right; padding:10px; border-bottom:1px solid #ccc;">
                                                                    <span class="lesson_duration">
                                                                        {{ lesson.duration | floatformat:2 }}
                                                                    </span>
                                                                </td>
                                                            </tr>
                                                        {% endfor %}
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
    