accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('users/', include([
        path('my-courses', views.EnrolledCoursesListView.as_view(), name='enrolled-courses'),
        path('my-courses/<slug:slug>/view', views.StartLessonView.as_view(), name='course-lessons'),
        path('my-courses/<slug:slug>/lessons/<int:id>', views.LessonView.as_view(), name='course-lessons-single'),
        path('user', views.UserUpdateView.as_view(), name='my-user'),
        path('my-profile', views.ProfileUpdateView.as_view(), name='my-profile'),
    ])),
]

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('courses/<slug:slug>/edit', CourseUpdateView.as_view(), name='course-edit'),
    path('courses/create', CourseCreateView.as_view(), name='course-create'),
    path('courses/lessons/<int:pk>/edit', LessonUpdateView.as_view(), name='course-lesson-edit'),
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='course-details'),
    path('courses/<slug:slug>/lessons', LessonsListView.as_view(), name='course-lessons'),
    path('courses/<slug:slug>/category', CoursesByCategoryListView.as_view(), name='course-by-category'),
]

lms/urls.py
from django.urls import path
from .views import *

app_name = 'lms'

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='search'),
]

lmspro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from lmspro import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('lms.urls')),
    path('', include('courses.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import now

from accounts.models import User
from django import forms


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)


class Course(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    slug = models.SlugField(max_length=200, unique=True, primary_key=True, auto_created=False)
    short_description = models.TextField(blank=False, max_length=120)
    description = models.TextField(blank=False)
    outcome = models.CharField(max_length=200)
    requirements = models.CharField(max_length=200)
    language = models.CharField(max_length=200)
    price = models.FloatField(validators=[MinValueValidator(9.99)])
    level = models.CharField(max_length=20)
    thumbnail = models.ImageField(upload_to='thumbnails/')
    video_url = models.CharField(max_length=100)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=100)
    duration = models.FloatField(validators=[MinValueValidator(0.30), MaxValueValidator(30.00)])
    video_url = models.CharField(max_length=100)
    documents = models.FileField(upload_to='documents/', blank=True, null=True)
    handson_url= models.CharField(max_length=100,  blank=True, null=True)
    created_at = models.DateTimeField(default=now)
    updated_at = models.DateTimeField(default=now)

    def __str__(self):
        return self.title

courses/forms.py
from django import forms
from .models import *
  
class CourseForm(forms.ModelForm):
  
    class Meta:
        model = Course
        fields = ['title', 'category', 'short_description', 'description', 'outcome', 'requirements', 'language', 'level', 'thumbnail', 'price', 'video_url' ,'is_published' ]

    def save(self, commit=True):
        course = super(CourseForm, self).save(commit=False)
        if commit:
            course.save()
        return course

class LessonForm(forms.ModelForm):
  
    class Meta:
        model = Lesson
        fields = ['title', 'video_url', 'duration', 'documents', 'handson_url']

    def save(self, commit=True):
        lesson = super(LessonForm, self).save(commit=False)
        if commit:
            lesson.save()
        return lesson

courses/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from cart.cart import Cart
from courses.forms import CourseForm, LessonForm
from courses.models import Course, Category, Lesson
from lms.models import Enroll


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/details.html'
    context_object_name = 'course'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        slug = self.kwargs.get(self.slug_url_kwarg)
        slug_field = self.get_slug_field()
        queryset = queryset.filter(**{slug_field: slug})
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404("No %(verbose_name)s found matching the query" %
                          {'verbose_name': self.model._meta.verbose_name})
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object(self.get_queryset())
        if self.request.user.is_authenticated:
            if Enroll.objects.filter(course=course, user_id=self.request.user.id).exists():
                context['is_enrolled'] = True
            else:
                cart = Cart(self.request)
                context['is_in_cart'] = cart.has_course(course)
        else:
            cart = Cart(self.request)
            context['is_in_cart'] = cart.has_course(course)
        return context


class CoursesByCategoryListView(ListView):
    model = Course
    template_name = 'courses/courses_by_category.html'
    context_object_name = 'courses'

    def get_queryset(self):
        category = Category.objects.get(slug=self.kwargs['slug'])
        return self.model.objects.filter(category=category.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(slug=self.kwargs['slug'])
        context['category'] = category
        context['categories'] = Category.objects.all()
        return context

class CourseCreateView(CreateView):
    # fields = ['title', 'category', 'short_description', 'description', 'outcome', 'requirements', 'language', 'level', 'thumbnail', 'video_url' ,'is_published' ]
    model = Course
    template_name = 'courses/course_form.html'
    success_url = '/login'
    form_class = CourseForm 

    extra_context = {
        'title': 'Kurs Oluştur'
    }

    # def dispatch(self, request, *args, **kwargs):
    #     if self.request.user.is_authenticated:
    #         return super().dispatch(self.request, *args, **kwargs)
    #     return HttpResponseRedirect(self.get_success_url())

    # def get_success_url(self):
    #     return self.success_url

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        
        return super(CourseCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):

        course_form = self.form_class(data=request.POST, files=request.FILES)
        self.object = course_form.save(commit=False)
        self.object.user = self.request.user
        if self.form_valid(course_form):
            course = course_form.save()
            course_form.save_m2m()
            return redirect('courses:edit', pk=course.id)
        else:
            return render(request, 'courses/course_form.html', {'form': course_form})


class CourseUpdateView(UpdateView):
    # fields = ['title', 'category', 'short_description', 'description', 'outcome', 'requirements', 'language', 'level', 'thumbnail', 'video_url' ,'is_published' ]
    model = Course
    template_name = 'courses/course_form.html'
    success_url = '/login'
    form_class = CourseForm 

    extra_context = {
        'title': 'Kurs Oluştur'
    }

    # def dispatch(self, request, *args, **kwargs):
    #     if self.request.user.is_authenticated:
    #         return super().dispatch(self.request, *args, **kwargs)
    #     return HttpResponseRedirect(self.get_success_url())

    # def get_success_url(self):
    #     return self.success_url

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        
        return super(CourseCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):

        course_form = self.form_class(data=request.POST, files=request.FILES)
        self.object = course_form.save(commit=False)
        self.object.user = self.request.user
        if self.form_valid(course_form):
            course = course_form.save()
            course_form.save_m2m()
            return redirect('courses:edit', pk=course.id)
        else:
            return render(request, 'courses/course_form.html', {'form': course_form})


class LessonsListView(ListView):
    model = Lesson
    template_name = 'lessons/lessons_list_by_course.html'
    context_object_name = 'lesson'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        lesson_id = self.kwargs['id']
        queryset = queryset.filter(id=lesson_id)
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
            url = obj.video_url
            url = url.replace("https://www.youtube.com/watch?v=", "https://www.youtube.com/embed/")
            obj.video_url = url
        except queryset.model.DoesNotExist:
            raise Http404("No %(verbose_name)s found matching the query" %
                          {'verbose_name': self.model._meta.verbose_name})
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = get_object_or_404(Course, slug=self.kwargs["slug"])
        context["lessons"] = self.model.objects.filter(course=course)
        context["course"] = course
        return context

class LessonUpdateView(UpdateView):
    # fields = ['title', 'category', 'short_description', 'description', 'outcome', 'requirements', 'language', 'level', 'thumbnail', 'video_url' ,'is_published' ]
    model = Lesson
    template_name = 'lessons/lesson_form.html'
    success_url = '/login'
    form_class = LessonForm 
    extra_context = {
        'title': 'Dersi Düzenle'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lesson = get_object_or_404(Lesson, pk=self.kwargs["pk"])
        course = Course.objects.get(slug=lesson.course.slug)
        context['course'] = course
        return context

    # def dispatch(self, request, *args, **kwargs):
    #     if self.request.user.is_authenticated:
    #         return super().dispatch(self.request, *args, **kwargs)
    #     return HttpResponseRedirect(self.get_success_url())

    # def get_success_url(self):
    #     return self.success_url

    def form_valid(self, form):
        self.object = form.save(commit=False)
        
        return super(LessonUpdateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        lesson = get_object_or_404(Lesson, pk=self.kwargs["pk"])
        lesson_form = self.form_class(data=request.POST, files=request.FILES, instance=lesson)
        if self.form_valid(lesson_form):
            lesson_form.save()
            lesson_form.save_m2m()
            return redirect('courses:course-lesson-edit', pk=lesson.id)
        else:
            return render(request, 'lessons/lesson_form.html', {'form': lesson_form})

templates/courses/course_form.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load total_minutes %}

{% block content %}

<section class="user-dashboard-area">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="user-dashboard-box">
                    <div class="user-dashboard-sidebar">
                        <div class="user-box">
                            <img src="/media/{{ course.thumbnail }}" alt="" class="img-fluid">
                            <div class="name">
                                <div class="name">
                                    {{ course.title }}
                                </div>
                            </div>
                        </div>
                        <div class="user-dashboard-menu">
                            <ul>
                                <li class="active"  >
                                    <a href="{% url 'courses:course-edit' course.slug %}">Temel Bilgiler</a>
                                </li>
                                <li >
                                    <a href="{% url 'accounts:my-profile' %}">Modüller</a>
                                </li>
                                <li >
                                    <a href="{% url 'accounts:my-profile' %}">Bölümler</a>
                                </li>
                                <li >
                                    <a href="{% url 'courses:course-lessons' course.slug %}">Dersler</a>
                                </li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="user-dashboard-content">
                        <div class="content-title-box">
                            <div class="title">Kurs Temel Bilgiler</div>
                            <div class="subtitle">Kurs Detayı için istediğiniz bilgileri girin.
                            </div>
                        </div>
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endif %}
                        <hr>
                        <form action="#" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            
                            <div class="content-box">
                                <div class="basic-group">
                                    {{ form|crispy }}
                                </div>
                                
                            </div>
                            <div class="content-update-box">
                                <button type="submit" class="btn">Güncelle</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/courses/courses_by_category.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}

    <section class="category-header-area">
        <div class="container-lg">
            <div class="row">
                <div class="col">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="/">
                                    <i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">
                                    {{ category.title }}
                                </a>
                            </li>
                        </ol>
                    </nav>
                    <h1 class="category-name">
                        {{ category.title }}
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <section class="category-course-list-area">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="category-filter-box filter-box clearfix">
                        <a href="" class="btn btn-outline-secondary all-btn">Tümü</a>

                        <div class="btn-group category-list">
                            <a class="btn btn-outline-secondary dropdown-toggle" href="#" data-toggle="dropdown">
                                Kategoriler
                            </a>
                            <div class="dropdown-menu">
                                {% for category in categories %}
                                    <a class="dropdown-item" href="{% url 'courses:course-by-category' category.slug %}">
                                        {{ category.title }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                    <div class="category-course-list">
                        <ul>
                            {% for course in courses %}
                                <li>
                                    <div class="course-box-2">
                                        <div class="course-image">
                                            <a href="{% url 'courses:course-details' course.slug %}">
                                                <img src="/media/{{ course.thumbnail }}" alt="" class="img-fluid">
                                            </a>
                                        </div>
                                        <div class="course-details">
                                            <a href="{% url 'courses:course-details' course.slug %}"
                                               class="course-title">{{ course.title }}</a>
                                            {#                                            {{--<a href="" class="course-instructor">--}}#}
                                            {#                                                {{--<span class="instructor-name">first_name last_name</span>--}}#}
                                            {#                                                {{-----}}#}
                                            {#                                            {{--</a>--}}#}
                                            <div class="course-subtitle">
                                                {{ course.short_description }}
                                            </div>
                                            <div class="course-meta">
                                                <span class="">
                                                    <i class="fas fa-play-circle"></i>
                                                    {{ course.lessons.count }} Ders
                                                </span>
                                                <span class="">
                                                    <i class="far fa-clock"></i>
                                                    3 saat
                                                </span>
                                                <span class="">
                                                    <i class="fas fa-closed-captioning"></i>{{ course.language }}
                                                </span>
                                            </div>
                                        </div>
                                        <div class="course-price-rating">
                                            <div class="course-price">
                                                <span class="current-price">₺{{ course.price }}</span>
                                                {#                                                {{--<span class="original-price">$300</span>--}}#}
                                            </div>
                                            <div class="rating">
                                                <i class="fas fa-star filled"></i>
                                                <i class="fas fa-star filled"></i>
                                                <i class="fas fa-star filled"></i>
                                                <i class="fas fa-star"></i>
                                                <span class="d-inline-block average-rating">5</span>
                                            </div>
                                            <div class="rating-number">
                                                33 Değerlendirme
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <nav>
                        {#                        {{ $courses->links() }}#}
                    </nav>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/courses/enrolled_courses.html
{% extends 'layouts/base.html' %}

{% load static %}
{% load accounts_tags %}
{% block content %}

    <section class="page-header-area my-course-area">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="page-title">Kurslarım</h1>
                    <ul>
                        <li class="active"><a href="">Tüm Kurslar</a></li>
                        <li>
                            <a href="">İstek Listesi</a>
                        </li>
                        {% is_instructor request.user as isinstructor %}

                        {% if  isinstructor %}
                        <li>
                            <a href="/courses/create">Oluştur</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="my-courses-area">
        <div class="container">
            <div class="row align-items-baseline">
                <div class="col-lg-6">
                    <div class="my-course-filter-bar filter-box">
                        <span>Süz</span>
                        <div class="btn-group">
                            <a class="btn btn-outline-secondary dropdown-toggle all-btn" href="#"
                               data-toggle="dropdown">
                                Kategoriler
                            </a>

                            <div class="dropdown-menu">
                                {% for category in categories %}
                                    <a class="dropdown-item" href="#" id="">{{ category.title }}</a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="btn-group">
                            <a class="btn btn-outline-secondary dropdown-toggle" href="#" data-toggle="dropdown">
                                Eğitmenler
                            </a>

                            <div class="dropdown-menu">
                                {% for instructor in instructors %}
                                    <a class="dropdown-item" href="#" id="">{{ instructor.first_name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="btn-group">
                            <a href="" class="btn reset-btn" disabled>Temizle</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="my-course-search-bar">
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control"
                                       placeholder="Kurslarımda ara">
                                <div class="input-group-append">
                                    <button class="btn" type="submit"><i class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row no-gutters" id="my_courses_area">
                {% for enroll in enrolls %}

                    <div class="col-lg-3">
                        <div class="course-box-wrap">
                            <div class="course-box">
                                <a href="">
                                    <div class="course-image">
                                        <img src="/media/{{ enroll.course.thumbnail }}" alt="" class="img-fluid">
                                        <span class="play-btn"></span>
                                    </div>
                                </a>
                                <div class="course-details">
                                    <a href="">
                                        <h5 class="title">{{ enroll.course.title }}</h5>
                                    </a>
                                    <p class="instructors"></p>
                                    <div class="rating your-rating-box"
                                         data-toggle="modal" data-id="{{ enroll.course.id }}"
                                         data-target="#EditRatingModal">

                                        {#                                        @php#}
                                        {#                                        $my_rating = $enroll->course->review()['rating'];#}
                                        {#                                        @endphp#}
                                        {#                                        @for($i = 1; $i <= 5; $i++)#}
                                        {#                                        @if ($i <= $my_rating)#}
                                        {#                                        <i class="fas fa-star filled"></i>#}
                                        {#                                        @else#}
                                        {#                                        <i class="fas fa-star"></i>#}
                                        {#                                        @endif#}
                                        {#                                        @endfor#}
                                        <p class="your-rating-text" id="ratings">
                                            <span class="your">Değerlendirmeniz</span>
                                            <span class="edit">Düzenle</span>
                                        </p>
                                    </div>
                                </div>
                                <div class="row" style="padding: 5px;">
                                    <div class="col-md-6">
                                        <a href="{% url 'courses:course-details' enroll.course.slug %}" class="btn">Kurs Detayı
                                            </a>
                                    </div>
                                    <div class="col-md-6">
                                        <a href="{% url 'accounts:course-lessons' enroll.course.slug %}" class="btn float-right">Başla
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}

    <script>

        function courseModal(course_id) {
            {#alert($course_id);#}
            $('#course_id_for_rating').val(course_id);
        }

    </script>

{% endblock %}